### ISSUE TITLE
problem after update to last UEFI hotpatch

### ISSUE THREAD

**Issue by hillaliy** [RehabMan/HP-ProBook-4x30s-DSDT-Patch#10]
Hi
I have hp 840 G3 running MacOS 10.12.6
I update the patch repositories and now I have some problems:
1. sound work only on bluetooth or headphones build in speakers don't work.
2. battery show 0% all time
3. Volume / brightness keys don't work.
I add Problem reporting File

Can you help me?
[RehabMan.zip](https://github.com/RehabMan/HP-ProBook-4x30s-DSDT-Patch/files/1289566/RehabMan.zip)

**Comment by RehabMan** [comment]
Use the forums:
https://www.tonymacx86.com/threads/guide-hp-probook-elitebook-zbook-using-clover-uefi-hotpatch.232948/
