### ISSUE TITLE
Audio Codec

### ISSUE THREAD

**Issue by atheleron** [RehabMan/HP-ProBook-4x30s-DSDT-Patch#13]
Hi

I have HP ProBook 650 G1
Im new to this but maybe this can help

After upgrade to High Sierra 10.13.4 my audio problems got worse. Actually even before that sometimes I have audio, sometimes I don't even after clearing cache and few restart it work but mostly that was after few restarts.

Maybe I'm wrong but I found out that I need codec for my audio witch by default almost every hackingtosh needs so in my case with DPCIManager i found that i have audio with **IDT 92HD91BXX** codec and somehow my audio worked without extra fix but not always it depends from time to time so the simple solution is to add kext that have all codec instructions and apparently I have fix the issue at least for this HP Laptop my audio works!! for now :)

From same developer of Lilu.kext there is also AppleALC.kext as description says its *Native macOS HD audio for not officially supported codecs*

so maybe with download script as Lilu.kext you should also include [AppleALC.kext](https://github.com/vit9696/AppleALC) for HP laptops that have Microsoft HD Audio actually Realtek HD Audio it really fixes the codec audio problem

**Comment by RehabMan** [comment]
Currently, this guide does not use AppleALC.kext.
Maybe in the future.
For now the solution for lost audio is simple and is documented in the guide.
