### ISSUE TITLE
about Screen flicker 

### ISSUE THREAD

**Issue by idonknown** [RehabMan/HP-ProBook-4x30s-DSDT-Patch#14]
device:   hp 820 g1 with haswell 4600u
os:          macOS_10.13.6

after installing complete,i patch macOS with code from this project.

when backlight turns max, it works usual,
but if not ,I found that screen flickers unusual when I take video with my iPhone,
this dose happens on windows 10 or Debian stretch.

that make eyes tired, and i'm sorry for my broken English...

 abc$ kextstat| grep -i fake
   15    0 xxxx         org.netkas.driver.FakeSMC (1787) xxxx    <11 7 5 4 3 1>
   60    1 xxxx         org.rehabman.driver.FakePCIID (1.3.12) xxxx     <12 7 5 4 3 1>
   61    0 xxxx         org.rehabman.driver.FakePCIID.XHCIMux (1.3.12)  xxxx     <60 12 7 5 4 3 1>

abc$ kextstat | grep -i Graphics 
   17    0 xxxx         as.lvs1974.IntelGraphicsFixup (1.2.7) xxxx     <16 12 7 5 4 3 2 1>
   82   15 xxxx        com.apple.iokit.IOGraphicsFamily (519.20) xxxx     <12 7 5 4 3 1>
   94    5 xxxx         com.apple.AppleGraphicsDeviceControl (3.20.13) xxxx     <82 12 7 6 5 4 3 1>
  109    0 xxxx        com.apple.driver.AppleIntelHD5000Graphics (10.3.6) xxxx     <93 92 82 12 7 6 5 4 3 1>
  124    1 xxxx         com.apple.driver.AppleGraphicsControl (3.20.13) xxxx     <7 5 4 3 1>
  125    0 xxxx         com.apple.driver.AppleGraphicsDevicePolicy (3.20.13) xxxx     <124 94 82 12 11 7 6 5 4 3 1>

**Comment by RehabMan** [comment]
Use the forums for troubleshooting, not the github issues database.
