### ISSUE TITLE
install_downloads.sh fails to install HWMonitor.app

### ISSUE THREAD

**Issue by Memphiz** [RehabMan/HP-ProBook-4x30s-DSDT-Patch#15]
When installing everything via install_downloads.sh there are 2 issues for me with HWMonitor.app.

1. The installed version under /Applications/HWMonitor.app can't be started due to wrong filesystem permissions of the Growl.framework inside the app bundle
2. Once that is fixed the HWMonitor.app shows an insanely high fan speed in the title bar - the fan speed is shown correctly inside the HWMonitor settings were the "to be shown" items are selected though.

**Comment by RehabMan** [comment]
Fixed the permissions issue (just changed _install_subs.sh to not use sudo).
But I can't reproduce the problem you mention regarding fan speed. First, I don't know what you mean by "fan speed in the title bar".  You can place fan speed in the popup, or in the system menu bar, but not in the title bar (of the popup?
When I place the fan speed inside the menu bar, it works fine as it does also in the popup.

**Comment by Memphiz** [comment]
I meant system menu bar. Will try again once back from vacation - thx for the permission fix :)

**Comment by RehabMan** [comment]
You should try resetting your HWMonitor prefs file (it might be corrupt due to changes in each version).

It is located at ~/Library/org.hwsensors.HWMonitor.plist

**Comment by Memphiz** [comment]
removing that plist (found it in ~/Library/Preferences btw) doesn't change the issue ... very odd...

**Comment by RehabMan** [comment]
Working just fine here.  You will need to use the forums to upload PR files.

**Comment by Memphiz** [comment]
fixed with https://github.com/RehabMan/OS-X-FakeSMC-kozlek/pull/27
