### ISSUE TITLE
Please Help As no one is 

### ISSUE THREAD

**Issue by ProtoBoyGG** [RehabMan/HP-ProBook-4x30s-DSDT-Patch#17]
Hi , I have an HP Laptop
Model - AY513TX
Audio Codec according to Linux Dump : ALC 3227

I was trying to patch DSDT for Audio Fix 
What I have done : 

Pressed F4 on clover
Went to acpi origin folder copied All DSDT and SSDT .aml Files to a desktop folder called Test
opned terminal in that folder i.e. test
also had refs.txt whic were not blank
disassembled with terminal command : iasl -da -dl -fe refs.txt DSDT.aml SSDT*.aml
now went on opened the maci asl and opened the dsdt.dsl in it
clicked on patch selected your laptop patch layout id 3 fix (had already set the laptop patrches link in preferences)

now apply then close

then i clicked compile i got mdbg error
and now no one is answering how to solve this 

i also tried with refs.txt without the -da argument  same error

i also tried without refs with -da argument it yielded aeg1 error so removed the complete "if" block then compiled and got 0 errors and 165 warnings anyways saved this one as dsdt.aml in patched folder and rebooted still got no audio

i also tried without refs.txt and without -da argument got aeg1 error as previous upon ermoving if block i got 2 more errors hence was of no use

so now i want to know how to fix my audio and which is the right command to disassemblt first:

1.iasl -da -dl -fe refs.txt DSDT.aml SSDT*.aml
2.iasl -dl -fe refs.txt DSDT.aml SSDT*.aml
3.iasl -da -dl DSDT.aml SSDT*.aml
4.iasl -de DSDT.aml SSDT*.aml

which one and after i get error do i remove them or do something else
what to do with mdbg errors etc. 

please help me rehabman no one has helped and i have to get audio working
it's been few weeks i have been regularly trying multiple things

please help me for once and all

🙏

**Comment by ProtoBoyGG** [comment]
i also have dual booted with windows so have sherlock software to determine codecs as well installed 
but it shows many audio codecs i dont know which one to state im sharing a screen shot please tell which audio codec is mine
@RehabMan 

![Screenshot (2)](https://user-images.githubusercontent.com/28356342/55147095-014bb000-5103-11e9-94b2-a8db32076157.png)

**Comment by ProtoBoyGG** [comment]
@RehabMan  please help

**Comment by RehabMan** [comment]
This repo is only for ProBook/EliteBook/ZBook.
You should use the forums.
