### ISSUE TITLE
acpidump

### ISSUE THREAD

**Issue by praneethmendu** [RehabMan/HP-ProBook-4x30s-DSDT-Patch#5]
dear rehabman,

Just signed up for gitHub i.e. I am a super-noob so please tolerate my noobness.

I wanted to bring a couple of issues to your notice:

1) the acpidump method is not working, to be specific it claims there is no option -t when i type 

sudo acpidump -b -t DSDT -o dsdt.aml

the help in my terminal showed no -t option but in the ubuntu man-pages show a : -t, --table DSDT option. I will do a little of my own research and get back to you. 

2) Tell me if I got it right : If i use the DSDT=No boot flag and then open MaciASL the raw DSDT is already loaded and I don't need to extract anything I can start patching, right ?

I was really confused by that part.

3) I am working with a HP pavilion dv6-6128nr (sandy-bridge i5 with hd 3000 bios:F.1B ) and I am assuming the "ProBook 4x40s Sandy Bridge" is an appropriate patch.

when I try to save my raw DSDT I get the error "_HID suffix must be all hex digits" which I solve by changing ABCDEFGH to ABCDEF00

Then when I apply only the sandy bridge patch I get this error " 2579, 6126, syntax error, unexpected '}' "

the code around this line is (error is on the line with the closing curly brace) : 

```
               Method (_Q20, 0, NotSerialized)  // _Qxx: EC Query
                {
                    Store (0x20, IO80)
                    _Q1F ()
                    Sleep (0x14)
                    Notify (
                }
```

notice how Notify is incomplete.

I went back to my raw DSDT and in almost the same location I found this : 

```
                Method (_Q20, 0, NotSerialized)  // _Qxx: EC Query
                {
                    Store (0x20, IO80)
                    _Q1F ()
                    Sleep (0x14)
                    Notify (\_TZ.THRM, 0x80)
                }
```

I tried completing the Notify command from here but that just resulted in a big mess.
![screen shot 2016-08-20 at 12 35 38 pm](https://cloud.githubusercontent.com/assets/21146348/17833457/b35c632a-66d2-11e6-9ef5-a87b4b95a4e4.png)

my raw DSDT from Linux cat method: 
[ori_dsdt.aml.zip](https://github.com/RehabMan/HP-ProBook-4x30s-DSDT-Patch/files/428477/ori_dsdt.aml.zip)

**Comment by praneethmendu** [comment]
i tried -t and --table DSDT instead of -t DSDT but all are rejected by the same reason : illegal option : -t

I can see that the code u provided is an example on the ubuntu man page but this is the result i am getting. I will try on my dads work laptop when he is not around and report back shortly.

**Comment by praneethmendu** [comment]
i tried -t and --table DSDT instead of -t DSDT but all are rejected by the same reason : illegal option : -t

I can see that the code u provided is an example on the ubuntu man page but this is the result i am getting. I will try on my dads work laptop when he is not around and report back shortly.

**Comment by RehabMan** [comment]
Off-topic.  This repo/guide is not for your laptop.
Use the forums.
