### ISSUE TITLE
Trackpad not working in OSX after following guide

### ISSUE THREAD

**Issue by outlassn** [RehabMan/HP-ProBook-4x30s-DSDT-Patch#6]
Hello, I cannot get my trackpad to work after following the guide twice. It just started happening out of nowhere and since then I have completely re-formatted the drive and the EFI and reinstalled OSX but it is still not working. I have no idea whats going on- but I do know the trackpad works in the clover screen, so it is not broken. 

Please assist me in this matter, it will be greatly appreciated

-outlassn

Edit: I am running a HP Probook 450 G2.

**Comment by RehabMan** [comment]
The issues database is not the appropriate place for support.
Use the forum.
