### ISSUE TITLE
After 2017 April Apple OSX update, HP Elitebook 2170p boots to black screen

### ISSUE THREAD

**Issue by helgadeville** [RehabMan/HP-ProBook-4x30s-DSDT-Patch#7]
During boot process, Intel HD4000 driver is beeing run, then the screen dims rapidly and goes totally black - the backlight is turned off.
After some investigation - the problem is with IntelBacklight.kext. Deleting this module on the said Elitebook 2170p resolves the issue completely, moreover, the brightness slider and keys work properly.

**Comment by RehabMan** [comment]
The current code does not use IntelBacklight.kext on 10.12.
You must have not followed the guide or are using old code.
