### ISSUE TITLE
install_downloads.sh filas on Fusion drive setup

### ISSUE THREAD

**Issue by hvisage** [RehabMan/HP-ProBook-4x30s-DSDT-Patch#9]
```
Installing HPFanReset.efi to Error: volume / is not on GPT disk/EFI/CLOVER/drivers64UEFI
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
```

I know which disk to manually mount etc. just don't know how you might want to handle that case before I create pull request options.
(Oh yes, I've replaced my DVD with a hdd/ssd caddy to be able to setup the Fusion drive)

**Comment by RehabMan** [comment]
For Fusion setups, CoreStorage setups, and now even APFS setups, you must modify mount_efi.sh to mount your EFI partition properly.
The replacement code can be as simple as:
```
diskutil mount disk0s1 >/dev/null
echo /Volumes/EFI
```

**Comment by hvisage** [comment]
Ah!
SImple and elegant, haven't thought of that!
Thanks again for great help.
